name: base
channels:
- defaults
- conda-forge
- bokeh
dependencies:
# core packages
- nodejs
- pip
- nbdime
# code audit
- watermark
- pylint
- pytest
- autopep8
- pep8
- pylama
- flake8
- black
# notebook packages
- jupyterlab
- ipykernel
- notebook
- nb_conda_kernels
# jupyter lab extension
- jupyter_bokeh
- jupyter_conda
- jupyterlab-git
- jupyterlab_code_formatter
- jupyterlab-plotly-extension
- pip:
    - jupyterlab_latex




